---
title: "satscan adjustment"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(sf)

```

```{r}
#read in data
d1<-read.csv("./Data/MANHATTAN SUBSET CANCER.csv")

```

## Run Poisson regression 
outcome is observed cases in each census block, predictor is household size, offset is e_breast (age/sex adjusted expected cases)

```{r}
mod1<-glm(OBREAST~HH_SIZE, 
          family="poisson", 
          offset=log(EBREAST), #Denominator that adjusts for Age/sex distribution 
          data=d1) #Fit model


summary(mod1) #Summarize output
```

#Generate fitted values
```{r}
d1$pred_cases_breast<-predict(mod1, newdata=d1, type="response")
```

## Compare values adjusted with EBREAST vs our model fit

```{r}
trans.blue<- rgb(0,0,1, alpha=0.2)
plot(d1$HH_SIZE, log(d1$OBREAST/d1$EBREAST), bty='l', pch=16, col=trans.blue) #Plot RR for adjusting for age/sex vs RR when adjusting for age/sex/SES
abline(a=0.6823, b=-0.30, col='red')

#Observed vs expected
plot(log(d1$pred_cases_breast), log(d1$OBREAST), bty='l', pch=16, col=trans.blue) #Plot RR for adjusting for age/sex vs RR when adjusting for age/sex/SES
abline(a=0, b=1, col='red', lty=2)

#Residuals
plot(d1$OBREAST/d1$pred_cases_breast, bty='l', pch=16, col=trans.blue)
abline(h=1, lty=2, col='red')
```

```{r}
write.csv(d1,'./Data/MANHATTAN SUBSET CANCER adj.csv')
```

